const path         = require('path')
const ejs          = require('ejs')
const express      = require('express')
const uploader     = require('express-fileupload')
const bodyParser   = require('body-parser')
const cookieParser = require('cookie-parser')
const router       = require('./router.js') 

async function main(){
  console.warn(new Date(), 'App is running')
  const app = express()
  app.use(express.static(path.join(__dirname, 'public')))
  app.use(uploader())
  app.use(bodyParser.json())
  app.use(bodyParser.urlencoded({ extended: true }))
  app.use(cookieParser())
  app.set('views', path.join(__dirname, 'public/views'))
  app.set('view engine', 'html')
  app.engine('html', ejs.renderFile)

  //-- ROUTER
  app.get('/',                    router.index)
  app.get('/login',               router.login)
  app.get('/profile',             router.profile)
  app.get('/profile/:id',         router.profileView)
  app.get('/artists',             router.artists)
  app.get('/collections',         router.collections)
  app.get('/collection/new',      router.collectionNew)
  app.get('/collection/:id',      router.collection)
  app.get('/mint',                router.mint)
  app.get('/nft/:id',             router.nftView)
  app.get('/market',              router.market)
  app.get('/market/:query',       router.marketSearch)
  app.get('/faq',                 router.faq)
  app.get('/terms',               router.terms)
  app.get('/privacy',             router.privacy)
  app.get('/support',             router.support)
  app.get('/deeplink',            router.deeplink)

//-- XAPP
  app.get('/xapp',                router.xapp)
  app.get('/xapp/collections',    router.xappCollections)
  app.get('/xapp/collection/:id', router.xappCollection)
  app.get('/xapp/market',         router.xappMarket)
  app.get('/xapp/artists',        router.xappArtists)
  app.get('/xapp/nft/:id',        router.xappNftView)
  app.get('/xapp/profile/:id',    router.xappProfileView)

//-- API
  app.get('/api/test',            router.apiTest)
  app.get('/api/search/:query',   router.apiSearch)
  app.post('/api/user',           router.apiUserNew)
  app.put('/api/user',            router.apiUserSet)
  app.get('/api/user/:id',        router.apiUserGet)
  app.post('/api/avatar',         router.apiAvatar)
  app.post('/api/artwork',        router.apiArtwork)
  app.post('/api/metadata',       router.apiMetadata)
  app.post('/api/nft/mint',       router.apiNftMint)
  app.post('/api/nft/save',       router.apiNftSave)
  app.post('/api/offer/sell',     router.apiOfferSell)
  app.post('/api/offer/buy',      router.apiOfferBuy)
  app.post('/api/offer/save',     router.apiOfferSave)
  app.post('/api/offer/update',   router.apiOfferUpdate)
  app.get('/api/collections',     router.apiCollections)
  app.post('/api/collection/new', router.apiCollectionNew)
  app.get('/api/collection/:id',  router.apiCollectionGet)
  app.get('/api/*',               router.apiCatchAll)
  app.get('/notfound',            router.notFound)
  app.get('/*',                   router.notFound)
  app.listen(5000)
}

main()

// END